#!/usr/bin/env node
const { chromium } = require("playwright-core");
const baseUrl = process.env.SITE_URL || "http://127.0.0.1:8088/";
const origin = new URL(baseUrl).origin;
(async () => {
  const browser = await chromium.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const page = await context.newPage();
  const pageErrors = [], consoleErrors = [], thirdParty = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));
  page.on("console", (m) => { if (m.type() === "error") consoleErrors.push(m.text()); });
  page.on("request", (request) => { if (new URL(request.url()).origin !== origin) thirdParty.push(request.url()); });
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  if (await page.locator("h1").count() !== 1) throw new Error("expected one h1");
  if (await page.locator("#gallery img[loading=lazy][decoding=async]").count() !== 14) throw new Error("gallery loading count mismatch");
  console.log("PASS: semantic h1 and 14 responsive lazy gallery images");
  const fontProof = await page.evaluate(async () => { await document.fonts.ready; return { heading: getComputedStyle(document.querySelector("h1")).fontFamily, body: getComputedStyle(document.body).fontFamily, marcellus: document.fonts.check('400 32px "Marcellus"'), mulish: document.fonts.check('400 16px "Mulish"') }; });
  if (!fontProof.heading.startsWith("Marcellus") || !fontProof.body.startsWith("Mulish") || !fontProof.marcellus || !fontProof.mulish) throw new Error(`font gate failed ${JSON.stringify(fontProof)}`);
  console.log(`PASS: self-hosted fonts applied ${JSON.stringify(fontProof)}`);
  await page.evaluate(() => scrollTo(0, innerHeight * 1.2)); await page.waitForTimeout(350);
  if (!await page.locator("#stickyCta").evaluate((e) => e.classList.contains("visible"))) throw new Error("sticky CTA missing after hero exit");
  if (!await page.locator("#siteNav").evaluate((e) => e.classList.contains("is-condensed"))) throw new Error("navigation did not condense");
  console.log("PASS: mobile sticky CTA and condensed navigation");
  await page.locator("#gallery").scrollIntoViewIfNeeded(); await page.locator(".glightbox").first().click();
  await page.locator(".glightbox-container").waitFor({ state: "visible" }); await page.keyboard.press("Escape"); await page.locator(".glightbox-container").waitFor({ state: "hidden" });
  console.log("PASS: GLightbox opens and closes by keyboard");
  if (await page.locator("#mapShell iframe").count()) throw new Error("map loaded before explicit interaction");
  console.log("PASS: map is lazy and interaction-gated");
  if (thirdParty.length) throw new Error(`unexpected third-party request: ${thirdParty.join(" | ")}`);
  if (pageErrors.length || consoleErrors.length) throw new Error(`browser errors: ${pageErrors.concat(consoleErrors).join(" | ")}`);
  console.log("PASS: zero initial third-party requests and zero browser errors");
  await context.close();
  const reducedContext = await browser.newContext({ viewport: { width: 390, height: 844 }, reducedMotion: "reduce" });
  const reducedPage = await reducedContext.newPage(); await reducedPage.goto(baseUrl, { waitUntil: "domcontentloaded" });
  const reduced = await reducedPage.evaluate(() => ({ opacity: getComputedStyle(document.querySelector(".reveal")).opacity, animation: getComputedStyle(document.querySelector(".hero-media img")).animationDuration, transition: getComputedStyle(document.querySelector(".gallery-item img")).transitionDuration }));
  if (reduced.opacity !== "1" || parseFloat(reduced.animation) > .00001 || parseFloat(reduced.transition) > .00001) throw new Error(`reduced motion failed ${JSON.stringify(reduced)}`);
  console.log(`PASS: reduced motion ${JSON.stringify(reduced)}`);
  await reducedContext.close(); await browser.close(); console.log("VERDICT: PASS");
})().catch((e) => { console.error(`FAIL: ${e.message}`); process.exit(1); });
